- name: Hello World Sample
  hosts: all
  tasks:
    - name: First message
      debug:
        msg: "The first message!"
    - name: Hello Message
      debug:
        msg: "Hello World {{ message }}!"
    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        seconds: 20

